name: Jumble App Build
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main
      - develop
      - feat/*
      - feature/*

jobs:
  Build-Jumble-App:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set image tag
        run: |
          branch=${GITHUB_REF#refs/heads/}
          if [ "$branch" == "main" ]; then
            echo "setting tag to latest"
            echo "TAG=latest" >> $GITHUB_ENV
          else
            short_sha=$(echo "${{ github.sha }}" | cut -c1-7)
            echo "setting tag to $short_sha" 
            echo "TAG=$short_sha" >> $GITHUB_ENV 
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: aartiimgs/jumble-app:${{ env.TAG }}
